### ISSUE TITLE
How can I resize the pixel buffer itself

### ISSUE THREAD

**Issue by clay53** [parasyte/pixels#125]
I want to be able to change the resolution the program is running at after initialization. I'm aware that `Pixels.resize(width: u8, height: u8)` resizes the surface the buffer is drawn on but that's not what I'm looking for. I've tried creating a new instance of pixels and replacing the old one like this: `pixels = pixels::PixelsBuilder::new(window_size.width, window_size.height, SurfaceTexture::new(window_size.width, window_size.height, &window)).enable_vsync(false).build().unwrap();`. However, this causes an error when attempting to render it again: [log.txt](https://github.com/parasyte/pixels/files/5673970/log.txt)

**Comment by parasyte** [comment]
The error is the same thing described in #121. There is a PR you can try in #122 It is not merge because there is an open question: https://github.com/parasyte/pixels/issues/121#issuecomment-719968913

Other than that, there isn't a method available for resizing the pixel buffer, just because I didn't need this for emulators of old hardware (.e.g with a fixed screen resolution). But I'm happy to accept contributions for a feature.

**Comment by clay53** [comment]
> The error is the same thing described in #121. There is a PR you can try in #122 It is not merge because there is an open question: [#121 (comment)](https://github.com/parasyte/pixels/issues/121#issuecomment-719968913)
> 
> Other than that, there isn't a method available for resizing the pixel buffer, just because I didn't need this for emulators of old hardware (.e.g with a fixed screen resolution). But I'm happy to accept contributions for a feature.

#122 doesn't seem to be working for what I want. I get a segmentation fault when I resize the window replacing the old instance of pixels to resize the pixel buffer. It does work when I do `pixels.resize()` but that was already working fine on my Linux machine which, I think, is what people are talking about isn't working in #121.

**Comment by parasyte** [comment]
To be clear, I was not suggesting that #122 would help. Just observing that the error is the same. #121 is about resizing the window and `wgpu` returning an error due to some race conditions.

Also looking over the attached log again, and it's clear that it doesn't really have enough context to troubleshoot. If you would like to provide a more complete example source, I think it can be useful to see what has already been tried before.

**Comment by LoganDark** [comment]
This is a huge deal breaker for me. `pixels` seemed like a good candidate to implement a fantasy computer, but if it does not support resizing the screen, I will have to look elsewhere (minifb?).

**Comment by parasyte** [comment]
I added the `help wanted` label to advertise that this feature is up for anyone who would like to implement it.
