### ISSUE TITLE
Weird grid on transparent windows?

### ISSUE THREAD

**Issue by jamuwu** [parasyte/pixels#156]
I've been making an application that is supposed to sit on top of another window. I'd like to make the window transparent, but doing so.. kinda ruins it
![](https://jamu.moe/s/C1W69g5715ua.png)

I thought that maybe it was just something I did wrong but it happens when I add transparency to the minimal-winit example too
![](https://jamu.moe/s/EXaOL7MTK205.png)

**Comment by parasyte** [comment]
That kind of looks like an issue with the surface texture size not matching the window inner size. It's hard to tell just looking at a screenshot. Maybe you can share the code used to create the window and handle resize? Also see #144 which had similar issues (in user code).

**Comment by jamuwu** [comment]
For that second screenshot, I quite literally just took the minimal-winit example and added `.with_transparency(true)` to the window builder.

**Comment by parasyte** [comment]
Adding `.with_transparent(true)` to `minimal-winit` doesn't have any issues on macOS. I definitely don't think this is our bug. Possibly fixed in `winit` by https://github.com/rust-windowing/winit/pull/1815

BTW, enabling transparency will not be enough (even with the linked patch) because `wgpu` doesn't support transparent windows: https://github.com/gfx-rs/wgpu/issues/687

**Comment by jamuwu** [comment]
For whatever reason, I can't reproduce this issue anywhere but my own pc. So I don't think there's a reason to keep it open.
