### ISSUE TITLE
[help wanted] black screen using with raqote

### ISSUE THREAD

**Issue by jiyinyiyong** [parasyte/pixels#199]
Long time since https://github.com/jrmuizel/raqote/issues/75 and I finally managed to made another attempt. https://github.com/calcit-lang/calcit-paint/blob/raqote-prototype/src/main.rs#L260-L288 but it only shew a black window on my macos. Could you help me locate the problem?

The example with `Shape::new(..)` worked on my laptop, I thought my code is mostly copied the logics, it should at least draw something. But got nothing.

**Comment by parasyte** [comment]
This isn't an issue in `pixels`, requests like this are better suited in the [discussions page](https://github.com/parasyte/pixels/discussions).

The bug in your code is this line: https://github.com/calcit-lang/calcit-paint/blob/b2c8768b019cc8b11d38ddf087debfdbe4c78279/src/main.rs#L272

You are cloning the pixel buffer and writing to a clone that `pixels` will never be able to see. Delete this line and it shows white text on a black background. (I do not know what the expected result is, but this is better than a pure black screen).

<img width="1112" alt="Screen Shot 2021-09-07 at 11 38 18 AM" src="https://user-images.githubusercontent.com/456942/132394612-ef710078-b579-4acf-9475-035465a660c1.png">

Since this isn't a bug on our end, I'll close this issue. If you would like further assistance, please create a new discussion thread! I'll be glad to help in any way I can.

**Comment by JMS55** [comment]
@parasyte btw, discussion page is not enabled for this repo

**Comment by parasyte** [comment]
😐 Dang, I can see the tab on my side. Thanks GitHub for not being helpful at all!

**Comment by jiyinyiyong** [comment]
Thanks for the help.

Maybe "Convert to Discussion"? I don't have permission on my side.
