### ISSUE TITLE
Renderer from Canvas support

### ISSUE THREAD

**Issue by Zageron** [parasyte/pixels#309]
Problem:
I cannot run pixels in the shadow root.
Current create surface ends up running in to this:
https://github.com/gfx-rs/wgpu/blob/master/wgpu-hal/src/gles/web.rs#L117

Solution:
Offer an interface that allows the use of a canvas instead of requiring a canvas to be found on the window.
https://github.com/parasyte/pixels/blob/main/src/builder.rs#L259

Using either or of these interfaces would be very helpful:
https://github.com/gfx-rs/wgpu/blob/master/wgpu-hal/src/gles/web.rs#L32
https://github.com/gfx-rs/wgpu/blob/master/wgpu-hal/src/gles/web.rs#L53

**Comment by parasyte** [comment]
`pixels` does not know anything about your environment. There is no assumption that a canvas is found on the window, as far as `pixels` is aware. It's up to you to provide a _surface_ (not a canvas) that `wgpu` is capable of rendering to. IMHO, this is a `wgpu` issue because it is `wgpu` that expects to find a canvas element on the `RawWindowHandle` implementation.

Because `pixels` does not know anything about your environment, I'm very hesitant to have it learn what a canvas is.

**Comment by parasyte** [comment]
@Zageron I'm confident this isn't a `pixels` issue _per se_, but it's in our best interest to investigate and come up with an adequate solution. If you can provide some more info about how you've setup your DOM, I think we can either come up with a minimal reproduction to show to the `raw-window-handle` project developers, or maybe even come up with something better that works for your particular use case. I expect it will be the former/ But I have no way right now to create a repro that can be used to concretely show why this is a problem.

**Comment by Zageron** [comment]
Hey, thanks for the extensive response.

My full understanding:

I think the primary "issue" is that Pixels is fully generic, as you stated. WebGPU offers three interfaces:
`create_surface_from_canvas`
`create_surface_from_offscreen_canvas`
`create_surface`

Pixels uses `create_surface` because it is generic and accepts a `raw_window_handle::RawWindowHandle`, whereas the former two are specific to WebSys types (canvas types).

The generalized solution in wgpu:
```rs
let canvas: web_sys::HtmlCanvasElement = web_sys::window()
                .and_then(|win| win.document())
                .expect("Cannot get document")
                .query_selector(&format!("canvas[data-raw-handle=\"{}\"]", handle.id))
                .expect("Cannot query for canvas")
                .expect("Canvas is not found")
                .dyn_into()
                .expect("Failed to downcast to canvas type");
```
means that it expects `query_selector` to be able to find an element in the page with the `data-raw-handle` property.

My Problem:
- I'm using Shadow Dom, using LIT, like react, to render a component that holds the canvas I am passing in to Winit and Pixels to be rendered. However, Shadow Dom components *cannot* be accessed by query_selector.

The Conundrum:
- There is no generalized interface in winit to support web's new "offscreen_canvas" functionality.
- There is not an explicit way to inform wgpu through Pixels to use an offscreen canvas. (This would add wasm specific functionality to Pixels and remove the fully generic feature.)

Solutions:
- Write my own renderer that accesses wgpu's `create_surface_from_canvas` similarly to how you access `create_surface` but create a non-generic interface for myself to render to web and native targets.
- Pixels offers an API for constructing web specific surfaces from either Canvas or Offscreen Canvas.

I will attempt to create an example repository today.

**Comment by parasyte** [comment]
> means that it expects `query_selector` to be able to find an element in the page with the `data-raw-handle` property.

Yep, that's a requirement from the `raw-window-handle` crate.

I think you're missing a third "solution" in your list, and that's allowing `HasRawWindowHandle` consumers (like `wgpu`) to gain access to a canvas without the need to query the DOM for it.

> My Problem:
> 
> * I'm using Shadow Dom, using LIT, like react, to render a component that holds the canvas I am passing in to Winit and Pixels to be rendered. However, Shadow Dom components _cannot_ be accessed by query_selector.

How would an app normally gain access to the `HtmlCanvasElement` or `WebGL2RenderingContext` from outside the shadow DOM? The most obvious approach I can think of is that component authors need to provide a method that returns these references, and applications are expected to call them instead of querying the DOM out-of-band.

This would be an architectural change for `raw-window-handle` and would likely involve a lot of people to make it happen. But it would also fix all apps using `raw-window-handle` with Shadow DOM components, and not just `wgpu` or just `pixels`.

**Comment by Zageron** [comment]
https://github.com/Zageron/pixels-shadow-dom-example

**Comment by parasyte** [comment]
We have some additional eyes on this issue now. Discussion has been upstreamed to https://github.com/rust-windowing/raw-window-handle/issues/102.

**Comment by Zageron** [comment]
> We have some additional eyes on this issue now. Discussion has been upstreamed to [rust-windowing/raw-window-handle#102](https://github.com/rust-windowing/raw-window-handle/issues/102).

Thanks! I've been following all the discussions the past day, awesome development for Bevy if you didn't see it.
https://github.com/bevyengine/bevy/pull/6147#issuecomment-1264754143

**Comment by parasyte** [comment]
I saw that PR but not the specific comment, thanks. What I noticed about the PR is that it implements practically exactly what I expect `raw-window-handle` should be doing; an enum with `HtmlCanvasElement` and `OffscreenCanvas` variants. This type would better serve the community in a minimal shared dependency like RWH. :)

We'll see how it goes!

**Comment by Zageron** [comment]
I hate it, but I figured shadow dom out.
See new code in `index.js`.
https://github.com/Zageron/pixels-shadow-dom-example

![image](https://user-images.githubusercontent.com/1892473/193966753-cf64001e-ee62-4b08-a9c3-23c021b5c8ba.png)

**Comment by markusmoenig** [comment]
Is this the same reason why pixels does not work with the latest Tao version ?

**Comment by parasyte** [comment]
The latest version of `tao` requires `raw-window-handle` 0.5, which means it needs `wgpu` 0.14. #320 should fix it!
