### ISSUE TITLE
Export of minimal-egui fails to run

### ISSUE THREAD

**Issue by paulhazen** [parasyte/pixels#311]
Taking the contents of `examples/minimal-egui`, putting it into it's own directory, then changing the `Cargo.toml` file to replace `pixels = { path = "../.." }` with `pixels = "0.9.0"` consistently produces the following build error:

```
error: failed to select a version for `web-sys`.
    ... required by package `wgpu v0.12.0`
    ... which satisfies dependency `wgpu = "^0.12"` of package `pixels v0.9.0`
    ... which satisfies dependency `pixels = "^0.9"` of package `minimal-egui v0.1.0 (C:\sandbox\new\minimal-egui)`
versions that meet the requirements `^0.3.53` are: 0.3.60, 0.3.59, 0.3.58, 0.3.57, 0.3.56, 0.3.55, 0.3.54, 0.3.53

the package `wgpu` depends on `web-sys`, with features: `GpuBufferUsage` but `web-sys` does not have these features.


all possible versions conflict with previously selected packages.

  previously selected package `web-sys v0.3.58`
    ... which satisfies dependency `web-sys = "^0.3.53"` of package `wgpu v0.12.0`
    ... which satisfies dependency `wgpu = "^0.12"` of package `pixels v0.9.0`
    ... which satisfies dependency `pixels = "^0.9"` of package `minimal-egui v0.1.0 (C:\sandbox\new\minimal-egui)`

failed to select a version for `web-sys` which could resolve this conflict
```

I am admittedly new to rust - but it seems like this example should be able to be copy-pasted around to play with. Is there something dumb I'm doing or failing to do that's causing this to happen?

**Comment by paulhazen** [comment]
At first blush I didn't see any relevant issues related to this, but further exploration led me here: https://github.com/parasyte/pixels/discussions/275

If I'm reading it correctly, this example only works when building / referencing the pixels crate from source. IMHO there should be a disclaimer added to the minimal-equi README file that makes this clear.

**Comment by parasyte** [comment]
You can copy the examples out of the workspace, but you need to use the tagged tree if you are using a released version of the crate. E.g. the tag `0.9.0`: https://github.com/parasyte/pixels/tree/0.9.0/examples/minimal-egui which is compatible with the 0.9.0 release.

If you want to use example packages in the `main` branch, you need to reference the correct revision in the `Cargo.toml`:

```toml
pixels = { git = "https://github.com/parasyte/pixels.git", rev = "9f7896cd2f1c80989e8f29ec6e3b6687183250a4" }
```

Either way works. The crate is still fairly unstable, which explains the lack of patch releases. Pretty much every release has been a minor version on `0.*` which is treated the same as a major version bump.

**Comment by paulhazen** [comment]
Thanks for the pointer! As someone newer to the rust / crate ecosystem, how typical is it for packages to be unstable? Not a reflection oh you, more an observation of the ecosystem norms. The minor version should have been a clue in retrospect.

**Comment by parasyte** [comment]
It's a good question, but keep in mind that "stability" is kind of a misnomer. Just because an interface changes doesn't mean it is guaranteed to affect everyone using the crate. The important thing is that breaking changes are communicated in some way (we do it with SemVer) so that there are no surprises when upgrades are not just a simple matter of changing the version number you depend on.

In practice, I have done exactly that -- just increase the version number expecting a broken build -- and everything works flawlessly. This has happened on several occasions. It just happens that the APIs that changed and the ones that I use are disjoint sets. 😄 Sometimes that's the way it goes.

There are relatively few crates that are both insanely popular and at least 1.0. They have a lot of pressure to maintain compatibility for as long as possible. But _most_ crates are not in the "insanely popular" category, and they can be nimbler. They can afford to converge on the right design. I think that's the typical situation in the Rust ecosystem.

Also, these threads have relevant discussion:

- https://users.rust-lang.org/t/too-many-low-level-crates-are-still-at-0-x-x-and-unstable/61718
- https://users.rust-lang.org/t/deciding-whether-to-go-to-version-1-0-0-for-a-crate/69005

**Comment by paulhazen** [comment]
Thanks @parasyte - that makes a ton of sense. Keep up the good work! And thanks for the rust pointers... pun (probably) intended.
