### ISSUE TITLE
Rendered window content size is out of sync and padded

### ISSUE THREAD

**Issue by Abdillah** [parasyte/pixels#314]
I run the `raquote-winit` example in GNOME with Wayland and get the following result.

![image](https://user-images.githubusercontent.com/3030950/198174708-1b9cac4b-be39-462c-881e-3a8bedc14b44.png)

It is padded and the size is out of sync. This is the case in **animated render**.

For **static render**, at the first render (before the cursor enter or interact), the size is fine. But soon as I touch the window, it goes out of sync and padded as in the picture.

The padded is actually passing through, as my cursor become and edit handle on top of a terminal.

**Comment by parasyte** [comment]
Hi!

The border is expected when scaling to non-integer multiples.

When you say "the size is fine" on what I presume is he first frame shown... I assume you say this because it doesn't have a border in this case. That would actually be a bug. The image should always have a border when the window surface size is not an exact integer multiple of the pixel buffer size.

Without more information, I can only guess that there are two issues:

1. The window is not created with an appropriate size. According to the `winit` docs, setting the window's inner size is supported on Wayland. The size is configured here in the raqote demo: https://github.com/parasyte/pixels/blob/9f7896cd2f1c80989e8f29ec6e3b6687183250a4/examples/raqote-winit/src/main.rs#L23-L31
2. The surface is resized "late". Maybe the window manager only sends the resize event to the window after the first interaction. The resize event is handled here: https://github.com/parasyte/pixels/blob/9f7896cd2f1c80989e8f29ec6e3b6687183250a4/examples/raqote-winit/src/main.rs#L77-L80

Both of these are entirely contained in the example code, so the main library crate isn't affected. And because the issue described cannot be reproduced on Windows or macOS, it sounds like this is just another Wayland snowflake behavior as implemented in `winit`. (There are a lot of Wayland-only issues that we've already addressed, you can see some examples by going through the closed issues.)

This needs some more information and a closer investigation. But at the moment, I think the bug is not quite what is described.

**Comment by Abdillah** [comment]
Thanks! You're right down to the pixel. it is true that the resize event is send upon interaction.

The solution in my code (not the example, though) is to add similar to the `raqote-winit`, by listening to resize event and then add `pixels.resize_buffer` as well because it what makes the padding gone completely.

**Comment by parasyte** [comment]
Just keep in mind that the `resize_buffer()` method changes the physical resolution of the pixel frame buffer instead of just scaling. There is an open PR that attempts to implement non-integer scaling (while maintaining the highest quality sharp pixel definition): #262. The PR has some unresolved issues.

**Comment by Abdillah** [comment]
> resize_buffer() method changes the physical resolution 

Right, on the raqote-winit demo, I tried to resize the buffer but forgot that the `DrawingTarget` must be resized too. The result was such distortion.

> There is an open PR that attempts to implement non-integer scaling

That would be a great feature.

My main concern in the OP has been solved, so closing this..
