### ISSUE TITLE
Black screen on macOS Mojave

### ISSUE THREAD

**Issue by FloVanGH** [parasyte/pixels#87]
I've got black screen running the winit examples on macOS Mojave.

![image](https://user-images.githubusercontent.com/6715107/84105794-aa857a00-aa19-11ea-8588-e0c12f32534a.png)

**Comment by parasyte** [comment]
Related to #72 and #76

**Comment by parasyte** [comment]
I have added a [troubleshooting section](https://github.com/parasyte/pixels#troubleshooting) to the README, with instructions for requesting the high performance GPU. This should be enough to workaround this issue for now.

**Comment by FloVanGH** [comment]
After I've updated to macOS Catalina it works.

**Comment by LoganDark** [comment]
Apparently, everyone who's encountered this issue has just promptly updated their OS, preventing the maintainers from ever determining or fixing the problem.

Mojave is only 2 versions behind the latest version. It's also more significant than other versions because it's the first version to add dark mode AND the last version to support 32-bit programs. That means some people like me are never going to upgrade.

That said, I also cannot reproduce this issue. I would love to help, but you know...

**Comment by parasyte** [comment]
The most up-to-date information I have on this issue is that it relates to both the GPU hardware and version of Metal that ships with Mojave. I have seen black screens with integrated Intel GPUs, but not discrete AMD GPUs.

Apart from upgrading the OS, requesting the high performance GPU may be acceptable in most cases. There is still an issue with laptops that only have an Intel GPU and run Mojave, however...

**Comment by LoganDark** [comment]
> There is still an issue with laptops that only have an Intel GPU and run Mojave, however...

...and laptops which turn on automatic graphics switching every time you reboot, like mine.

**Comment by parasyte** [comment]
The last release of Mojave was July 21, 2021; 16 months ago. It has been succeeded by four major macOS releases. I think this can safely be closed and our official position should be "macOS Mojave is not supported".

**Comment by LoganDark** [comment]
What a great way to solve the issue, just wait until you can say the OS is not supported :)

**Comment by parasyte** [comment]
If you have a better solution, I will happily accept it.

Unfortunately there has been a lack of contributions on this particular issue, and I do not personally have a way to run macOS Mojave. And as you know, there are open issues on the `wgpu` repo for Mojave. And at least one that was closed (probably prematurely): https://github.com/gfx-rs/wgpu/issues/104

Regardless, I don't think there is anything we can do here except track an upstream issue (whether that's the closed one or something else?)
